### ISSUE TITLE
registerForActivityResult should be scalled before your activity is created

### ISSUE THREAD

**Issue by cempo** [Atwa/filepicker#1]
I'm getting error when launch a picker

LifecycleOwner MyActivity is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.

Reason: Related to android documentation, registerForActivityResult() is safe to call before your fragment or activity is created

How to do it for this library?

**Comment by Atwa** [comment]
@cempo Thanks for raising this, I will work on that bug.

**Comment by cempo** [comment]
Works correct. Thank you

**Comment by Atwa** [comment]
> Works correct. Thank you

Your welcome :)
