### ISSUE TITLE
Unable to load image taken from camera Android 13

### ISSUE THREAD

**Issue by mehrosh-teo** [Atwa/filepicker#15]
Glide is unable to load the image from the stored url e-g
/data/user/0/<package_name>/cache/1678789039
Device OS: Android 13
lib version: 1.0.5

**Comment by Atwa** [comment]
Hi @mehrosh-teo Sorry for that, this is already fixed in version 1.0.7 you can give it a try.

**Comment by mehrosh-teo** [comment]
> Hi @mehrosh-teo Sorry for that, this is already fixed in version 1.0.7 you can give it a try.

Thanks, worked like a charm !

**Comment by Atwa** [comment]
Most welcome, Happy to hear that.
