### ISSUE TITLE
Camera capture image quality 

### ISSUE THREAD

**Issue by yasir0899** [Atwa/filepicker#16]
@Atwa How to increase captureCameraImage quality like it giving me image in 40 KB which is not good in quality…
I tested it on emulator and on real device Android 9.0
Gallery selection image size is perfect and quality is also but capture image quality is not good.

**Comment by Atwa** [comment]
Hi @yasir0899 It came out that the image's thumbnail was getting picked instead of the original  image.
That's fixed now in latest version (1.0.8)
