### ISSUE TITLE
Not working with BottomSheetDialogFragment

### ISSUE THREAD

**Issue by roshan-personatech** [Atwa/filepicker#17]
Hi, I tried this library with the BottomSheetDialogFragment and found that the picker starts and lets us pick the file/image, but the doesn't give the result back.

**Comment by Atwa** [comment]
Hi I'm using it in BottomSheetDialogFragment in one of my production projects and it's working fine.
Just initiate it as member variable as following.

    private val filePicker = FilePicker.getInstance(this)
 Then you can start call the filepicker instance functions in onCreateView

**Comment by roshan-personatech** [comment]
Thanks, will try this.

**Comment by roshan-personatech** [comment]
Thanks, will try this.
