### ISSUE TITLE
issue with readme

### ISSUE THREAD

**Issue by hamza94max** [Atwa/filepicker#20]
![Capture](https://github.com/Atwa/filepicker/assets/54688005/205e01b8-fef0-416b-ada4-3a1394bde4c0)

``` kotlin
public abstract fun toRequestBody(
    file: File,
    type: MediaType?
): RequestBody
```

not 

``` kotlin
public abstract fun toRequestBody(
type: MediaType?,
    file: File
): RequestBody
```

as readme told

Thank you for helping me with this great library

**Comment by Atwa** [comment]
Thank you for raising this up, will fix it asap.
Happy coding:)
