### ISSUE TITLE
[Feature request] Get photo from camera

### ISSUE THREAD

**Issue by cempo** [Atwa/filepicker#3]
Would be great to have ability to take photo from camera using this library

val cameraIntent = Intent(MediaStore.ACTION_IMAGE_CAPTURE).apply {
                addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION)
                putExtra(MediaStore.EXTRA_OUTPUT, outputUri)
            }
            
And interface like:
fun pickImageFromCamera(outputUri: Uri, onImagePicked: (Pair<Bitmap?, File?>?) -> Unit)

**Comment by Atwa** [comment]
Thanks for sharing your valuable thoughts I will implement it ASA I'm free.

**Comment by Androbito** [comment]
yes we need it, it's useful

**Comment by Atwa** [comment]
@Androbito @cempo will be available on Sunday Inshallah

**Comment by Atwa** [comment]
@cempo @Androbito Feature is available now with version 1.4.0

**Comment by cempo** [comment]
Thank you for the update.

I'm getting gradle error: 
ResourceException: Could not get resource 'https://jcenter.bintray.com/com/github/Atwa/Android-FilePicker/1.0.4/Android-FilePicker-1.0.4.pom'.

**Comment by AbdElwahabZayed** [comment]
@cempo I think the version should be 1.4.0 not 1.0.4

**Comment by Atwa** [comment]
@cempo try with com.github.atwa:filepicker:1.0.4 instead of Android-FilePicker

**Comment by cempo** [comment]
Already working. Thanks

It would be great to have file with name which include extension like ".jpg" or ".jpeg". What do you think?
