### ISSUE TITLE
app icon override  

### ISSUE THREAD

**Issue by Androbito** [Atwa/filepicker#8]
Hi Atwa,
There is a problem with ic_launcher under anydpi-v26 folders that override icon apps when using the library, I think ic_launcher should be removed as it's a library project.
what do you think?
Regards

**Comment by Atwa** [comment]
@Androbito Thanks for letting me know.
Will fix that ASAP.

**Comment by aanalmehta** [comment]
Hey, can you please fix this ASAP? I am getting the same error and because of that, I am getting ManifestMerger error.

**Comment by Atwa** [comment]
@Androbito @aanalmehta Fixed now in release 1.0.5
Sorry for late reply
