### ISSUE TITLE
use in fragment

### ISSUE THREAD

**Issue by marzieNoor** [Atwa/filepicker#9]
Hi Atwa
how to use this methods in fragment?
when I use in fragment , I get this Err:

java.lang.IllegalStateException: LifecycleOwner MyPakageName.ui.MainActivity@69347ae is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.

thanks

**Comment by Atwa** [comment]
Hi @marzieNoor,
add this to the top of your fragment or in onCreate()
private val filePicker = FilePicker.getInstance(requireActivity())

Then use corresponding functions with filePicker instance but after ui is inflated

**Comment by marzieNoor** [comment]
I try it before but i got same Error and crashed my application
 
othewise when add this line to fragment , we have a 'Type mismatch' error:

Type mismatch.
Required:
AppCompatActivity
Found:
FragmentActivity

Even if we cast it to 'AppCompatActivity' or 'MainActivity', the crash problem will not be solved
and the previous error is still there

thanls

**Comment by Atwa** [comment]
@marzieNoor Oh sorry for such a bad experience.
Will resolve it and update you ASAP

**Comment by marzieNoor** [comment]
@Atwa 
thank you Awta

**Comment by Atwa** [comment]
Hi @marzieNoor  You can now use the library with fragments safely the same way you initialize it in activity.
